Kobus/Models/Voyage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Kobus.Models
{
    public class Voyage
    {
        public string Route { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Capacity { get; set; }
        public string TicketPrice { get; set; }
        public string Plaqa { get; set; }
        public string Captain { get; set; }
        public string Bus { get; set; }
    }
}

Kobus/Controllers/KobusController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kobus.Entity;
using Kobus.Globals;
using Kobus.Substructure;

namespace Kobus.Controllers
{
    public class KobusController : Controller
    {
        // GET: Kobus

        Entity.Entity entity = new Entity.Entity();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult LoginEmployee()
        {
            return View();
        }

        public ActionResult Sefer()
        {
            Globals.Globals.FileBus = Path.Combine(Server.MapPath("~/File/"));
            Globals.Globals.VoyageListLength();
            Globals.Globals.FileControl();
            return View();
        }
        public JsonResult VoyageAdd(Models.Voyage Voyage)
        {
            DoubleDirectionalList VoyageList = new DoubleDirectionalList();
            IFormatProvider culture = new CultureInfo("tr-TR", true);
            DateTime date = DateTime.ParseExact(Voyage.Date, "yyyy-MM-dd", culture);
            Voyage.Date = Globals.Globals.DATEFILE(date);
            VoyageList.Add(Convert.ToInt32(Globals.Globals.Length));
            VoyageList.Add(Voyage.Route);
            VoyageList.Add(Voyage.Date);
            VoyageList.Add(Voyage.Time);
            VoyageList.Add(Voyage.Capacity);
            VoyageList.Add(Voyage.TicketPrice);
            VoyageList.Add(Voyage.Plaqa);
            VoyageList.Add(Voyage.Captain);
            VoyageList.Add(Voyage.Bus);
            entity.VoyageAdd(VoyageList, Voyage.Capacity);
            entity.Days(Voyage.Date, VoyageList , Voyage.Capacity);
            return Json("");
        }

        public JsonResult VoyageEditData(int data)
        {
            Globals.Globals.Data = data;
            Models.Voyage voyage = new Models.Voyage();
            DoubleDirectionalList List = entity.VoyageList(data);
            IFormatProvider culture = new CultureInfo("tr-TR", true);
            DateTime date = DateTime.ParseExact(List.Data(2).ToString(),"dd.MM.yyyy",culture);
            string DateHTML = Globals.Globals.DATEHTML(date); 
            voyage.Route = List.Data(1).ToString();
            voyage.Date = DateHTML;
            voyage.Time = List.Data(3).ToString();
            voyage.Capacity = List.Data(4).ToString();
            voyage.TicketPrice = List.Data(5).ToString();
            voyage.Plaqa = List.Data(6).ToString();
            voyage.Captain = List.Data(7).ToString();
            voyage.Bus = List.Data(8).ToString();
            return Json(voyage);
        }
        public JsonResult VoyageEdit(Models.Voyage Voyage)
        {
            DoubleDirectionalList VoyageList = new DoubleDirectionalList();
            IFormatProvider culture = new CultureInfo("tr-TR", true);
            DateTime date = DateTime.ParseExact(Voyage.Date, "yyyy-MM-dd", culture);
            Voyage.Date = Globals.Globals.DATEFILE(date);
            VoyageList.Add(Globals.Globals.Data);
            VoyageList.Add(Voyage.Route);
            VoyageList.Add(Voyage.Date);
            VoyageList.Add(Voyage.Time);
            VoyageList.Add(Voyage.Capacity);
            VoyageList.Add(Voyage.TicketPrice);
            VoyageList.Add(Voyage.Plaqa);
            VoyageList.Add(Voyage.Captain);
            VoyageList.Add(Voyage.Bus);
            entity.VoyageEdit(VoyageList, Globals.Globals.Data);
            return Json("");

        }
        public JsonResult VoyageDelete(int data)
        {
            Globals.Globals.VoyageCapacity(data);
            foreach (var item in Globals.Globals.Capacity)
            {
                if (item != "Null")
                {
                    entity.Log(DateTime.Now + " - HATA!" + data + "numaralı sefer iptal edilemez");
                    return Json("Sefer İptal Edilemez");
                }
            }
            entity.VoyageDelete(data);
            return Json("Silindi");
        }
        public ActionResult DeletedVoyageList()
        {
            Globals.Globals.FileBus = Path.Combine(Server.MapPath("~/File/"));
            Globals.Globals.VoyageListLength();
            Globals.Globals.FileControl();
            return View();
        }
        public ActionResult HistoryVoyageList()
        {
            Globals.Globals.FileBus = Path.Combine(Server.MapPath("~/File/"));
            Globals.Globals.VoyageListLength();
            Globals.Globals.FileControl();
            return View();
        }
        public JsonResult BackToDeletedVoyage(int data)
        {
            entity.VoyageBackToDeleted(data);
            return Json("");
        }
        public ActionResult BiletEmployee()
        {
            return View();
        }
        public ActionResult BiletAdmin()
        {
            Globals.Globals.FileBus = Path.Combine(Server.MapPath("~/File/"));
            Globals.Globals.VoyageListLength();
            Globals.Globals.FileControl();
            return View();
        }
        public JsonResult TicketCapacity(int data)
        {
            Globals.Globals.Data = data;
            Globals.Globals.VoyageCapacity(data);
            return Json(Globals.Globals.Capacity);
        }
        public ActionResult BiletAl()
        {
            return View();
        }
        public JsonResult TicketBuy(string[] koltuknumarasi, string[] adsoyad, string[] cinsiyet, string durum)
        {
            for (int i = 0; i < koltuknumarasi.Length; i++)
            {
                entity.TicketBuy(koltuknumarasi[i], adsoyad[i], cinsiyet[i], durum);
            }
            Globals.Globals.VoyageCapacity(Globals.Globals.Data);
            return Json("");
        }
        public JsonResult TicketClose(int data)
        {
            Globals.Globals.Capacity[data] = "Null";
            entity.TicketClose(Globals.Globals.Capacity);
            return Json("");
        }
        public ActionResult AllVoyageList()
        {
            Globals.Globals.FileBus = Path.Combine(Server.MapPath("~/File/"));
            Globals.Globals.VoyageListLength();
            Globals.Globals.FileControl();
            return View();
        }

    }
}

Kobus/Views/Kobus/AllVoyageList.cshtml
@using Kobus.Entity;
@using Kobus.Substructure;
@using Kobus.Globals;
@{
    ViewBag.Title = "AllVoyageList";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="normaltext">
    <div class="hakdiv"
         id="divhak"
         style="display: block; margin: 0 auto; margin-top:15px; margin-bottom: 160px;">

        <center>
            <div class="CardDiv">
                <div class="GreenTitleDiv">
                    <h3 style=" float:left; margin-top: 1px; margin-left: 8px; padding-left: 6px; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">Tüm Seferler</h3>
                </div>
                <div class="row offset-2 custyle" style="padding:5px; margin:10px 10px 10px 0px; ">
                    <table class="table table-striped custab" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size:14px;  ">
                        @{Entity entity = new Entity();
                            DoubleDirectionalList Voyage = entity.VoyageList(0);
                            Node temp = Voyage.top;

                            <thead style="padding-left:90px; padding-right:90px;">
                                <tr style="padding-left:90px; padding-right:90px;">
                                    @while (temp != null)
                                    {
                                        <th>@temp.Data</th>
                                        temp = temp.Next;
                                    }
                                </tr>
                            </thead>


                            for (int i = 1; i < Convert.ToInt32(Globals.Length); i++)
                            {
                                Voyage = entity.VoyageList(i);
                                temp = Voyage.top;
                                <tr>

                                    @for (int j = 0; j < Voyage.Count(); j++)
                                    {
                                        <td>@Voyage.Data(j)</td>
                                    }
                                    <td>@Convert.ToInt32(entity.VoyageTotalBudget(@i) * Convert.ToInt32(Voyage.Data(5)))<span class="simge-tl">&#8378;</span> </td>
                                    <td>@Voyage.Data(4) / @entity.VoyageTotalBudget(@i)</td>
                                </tr>
                            }
                        }
                    </table>
                </div>
                <br />
                <br />
            </div>
            <a class="btn btn-warning" style="font-size:14px;color:white; font-weight:500; font-family:'Segoe UI'" href="/Kobus/Sefer">Sefer Listesi</a>
        </center>
    </div>
</div>

Kobus/Views/Kobus/BiletAdmin.cshtml
@using Kobus.Entity;
@using Kobus.Substructure;
@using Kobus.Globals;
@{
    ViewBag.Title = "BiletAdmin";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="normaltext">
    <div class="hakdiv"
         id="divhak"
         style="display: block; margin: 0 auto; margin-top:15px; margin-bottom: 160px;">

        <center>
            <div class="CardDiv">
                <div class="GreenTitleDiv">
                    <h3 style=" float:left; margin-top: 1px; margin-left: 8px; padding-left: 6px; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">Bilet iİşlemleri &#10142; Sefer Listeleme: Sefer Seçme</h3>
                </div>

                <div class="row offset-2 custyle" style="padding:5px; margin:10px 10px 10px 0px; ">
                    <table class="table table-striped custab" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size:14px;  ">
                        @{Entity entity = new Entity();
                            DoubleDirectionalList Voyage = entity.VoyageList(0);
                            Node temp = Voyage.top;

                            <thead style="padding-left:90px; padding-right:90px; ">
                                <tr style="padding-left:90px; padding-right:90px; ">
                                    @while (temp != null)
                                    {
                                        <th>@temp.Data</th>
                                        temp = temp.Next;
                                    }
                                </tr>
                            </thead>


                            for (int i = 1; i < Convert.ToInt32(Globals.Length); i++)
                            {

                                if (Globals.filecontrol[i] == "Active")
                                {
                                    Voyage = entity.VoyageList(i);
                                    temp = Voyage.top;
                                    <tr>
                                        @for (int j = 0; j < Voyage.Count(); j++)
                                        {
                                            <td>@Voyage.Data(j)</td>
                                        }
                                        <td>@Convert.ToInt32(entity.VoyageTotalBudget(@i) * Convert.ToInt32(Voyage.Data(5)))<span class="simge-tl">&#8378;</span> </td>
                                        <td>@Voyage.Data(4) / @entity.VoyageTotalBudget(@i)</td>
                                        <td class="text-center" style="float:right;">
                                            <a class="btn btn-warning" style="font-size:14px;color:white; font-weight:500 " onclick="showDiv(@i)"><span class="glyphicon glyphicon-remove"></span>Sefer Seç</a>
                                        </td>
                                    </tr>
                                }

                            }
                        }
                    </table>
                </div>
                <br />
                <br />
            </div>
        </center>
        <br />
        <br />
    </div>

    <!-- Modal -->
    <script type="text/javascript">
        function showDiv(data) {
            $.ajax({
                url: '/Kobus/TicketCapacity/',
                data: { data: data },
                type: 'POST',
                success: function () {
                    window.location.href = "/Kobus/BiletAl";
                }
            });
        }
    </script>
</div>

Kobus/Views/Kobus/DeletedVoyageList.cshtml
@using Kobus.Entity;
@using Kobus.Substructure;
@using Kobus.Globals;
@{
    ViewBag.Title = "DeletedVoyageList";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="normaltext">
    <div class="hakdiv"
         id="divhak"
         style="display: block; margin: 0 auto; margin-top:15px; margin-bottom: 160px;">

        <center>
            <div class="CardDiv">
                <div class="GreenTitleDiv">
                    <h3 style=" float:left; margin-top: 1px; margin-left: 8px; padding-left: 6px; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">Silinen Sefer Listesi</h3>
                </div>

                <div class="row offset-2 custyle" style="padding:5px; margin:10px 10px 10px 0px; ">
                    <table class="table table-striped custab" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size:14px;  ">
                        @{Entity entity = new Entity();
                            DoubleDirectionalList Voyage = entity.VoyageList(0);
                            Node temp = Voyage.top;

                            <thead>
                                <tr>
                                    @while (temp != null)
                                    {
                                        <th>@temp.Data</th>
                                        temp = temp.Next;
                                    }
                                </tr>
                            </thead>


                            for (int i = 1; i < Convert.ToInt32(Globals.Length); i++)
                            {
                                if (Globals.filecontrol[i] == "Null")
                                {
                                    Voyage = entity.VoyageList(i);
                                    <tr>

                                        @for (int j = 0; j < Voyage.Count(); j++)
                                        {
                                            <td>@Voyage.Data(j)</td>
                                        }
                                        <td>@Convert.ToInt32(entity.VoyageTotalBudget(@i) * Convert.ToInt32(Voyage.Data(5)))<span class="simge-tl">&#8378;</span> </td>
                                        <td>@Voyage.Data(4) / @entity.VoyageTotalBudget(@i)</td>
                                        <td class="text-center"><a class='btn btn-dark' style="font-size:14px; font-weight:500; font-family:'Segoe UI'" onclick="BackTo(@i)" data-toggle="modal" data-target="#cart"><span class="glyphicon glyphicon-edit"></span>Geri AL</a>
                                    </tr>
                                }
                            }
                        }
                    </table>
                </div>

            </div>
            <a class="btn btn-warning" style="font-size:14px;color:white; font-weight:500; font-family:'Segoe UI'" href="/Kobus/Sefer">Sefer Listesi</a>
        </center>
    </div>
    <script type="text/javascript">
        function BackTo(data) {
            $.ajax({
                url: '/Kobus/BackToDeletedVoyage',
                data: { data: data },
                type: 'POST',
                success: function () {
                    alert("Geri Alındı");
                    window.location.reload();
                }
            });
        }
    </script>
</div>

Kobus/Views/Kobus/HistoryVoyageList.cshtml
@using Kobus.Entity;
@using Kobus.Substructure;
@using Kobus.Globals;
@{
    ViewBag.Title = "HistoryVoyageList";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="normaltext">
    <div class="hakdiv"
         id="divhak"
         style="display: block; margin: 0 auto; margin-top:15px; margin-bottom: 160px;">

        <center>
            <div class="CardDiv">
                <div class="GreenTitleDiv">
                    <h3 style=" float:left; margin-top: 1px; margin-left: 8px; padding-left: 6px; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">Geçmiş Seferler</h3>
                </div>
                <div class="row offset-2 custyle" style="padding:5px; margin:10px 10px 10px 0px; ">
                    <table class="table table-striped custab" style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size:14px;  ">
                        @{Entity entity = new Entity();
                            DoubleDirectionalList Voyage = entity.VoyageList(0);
                            Node temp = Voyage.top;

                            <thead style="padding-left:90px; padding-right:90px;">
                                <tr style="padding-left:90px; padding-right:90px;">
                                    @while (temp != null)
                                    {
                                        <th>@temp.Data</th>
                                        temp = temp.Next;
                                    }
                                </tr>
                            </thead>


                            for (int i = 1; i < Convert.ToInt32(Globals.Length); i++)
                            {
                                Voyage = entity.VoyageList(i);
                                temp = Voyage.top;
                                if (Globals.filecontrol[i] == "History")
                                {
                                    <tr>

                                        @for (int j = 0; j < Voyage.Count(); j++)
                                        {
                                            <td>@Voyage.Data(j)</td>
                                        }
                                        <td>@Convert.ToInt32(entity.VoyageTotalBudget(@i) * Convert.ToInt32(Voyage.Data(5)))<span class="simge-tl">&#8378;</span> </td>
                                        <td>@Voyage.Data(4) / @entity.VoyageTotalBudget(@i)</td>
                                    </tr>
                                }
                            }
                        }
                    </table>
                </div>
                <br />
                <br />
            </div>
            <a class="btn btn-warning" style="font-size:14px;color:white; font-weight:500; font-family:'Segoe UI'" href="/Kobus/Sefer">Sefer Listesi</a>
        </center>
    </div>
</div>

Kobus/Views/Kobus/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/LoginLayout.cshtml";
}

<script>
            function Giris() {
                var id = document.getElementById("Yonetici").value;
                var sifre = document.getElementById("Yoneticisifre").value;

                if (id == "admin" && sifre == "admin") {
                   window.open('@Url.Action("Sefer", "Kobus")');
            }
        }
</script>

<div class="container" style="margin-top:100px">
    <div class="row">

        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h1 style="text-align:center">
                        <img src="~/img/hosgeldin.png" style="width:150px; height:105px" alt="">

                    </h1>
                    <h5 style="text-align:center;color:white; font-size:14px; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Yönetici Olarak Devam Etmek İçin Giriş Yapın</h5>
                    @ViewBag.Mesaj
                    @using (Html.BeginForm("Login", "Kobus", FormMethod.Post))
                    {
                        <form class="form-signin">
                            <div class="form-label-group" style="color:white; font-size:15px">
                                <input type="text" id="Yonetici" name="lname" placeholder="Id" required class="inputt">
                            </div>
                            <div class="form-label-group" style="color:white; font-size:15px">
                                <input type="password" id="Yoneticisifre" name="lname" placeholder="Şifre" required class="inputt">
                            </div>
                            <div>
                                <p> </p>
                            </div>
                            <button type="submit" onclick="Giris()" class="btnn" style="width:100%; text-align:center; background-color:#5CD375;color:white;">Giriş Yap</button>
                            <hr class="my-4">
                        </form>

                    }
                    <p style="text-align:center; color:white;font-size:10px; font-family:'Segoe UI'">Giriş yaparak otomasyon Gizlilik Politikası’nı okuduğunuzu ve kabul ettiğinizi onaylıyorsunuz.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Kobus/Views/Shared/AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="theme-color" content="#272E36" />
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Yönetici</title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css"
          rel="stylesheet" />
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <link href="~/Content/css/styleslide.css" rel="stylesheet" />
    <link href="~/Content/css/Koltuk.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="~/img/FAV.png" />
    <!-- Bootstrap core CSS -->
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/business-casual.min.css" rel="stylesheet">
    <link href="../Content/css/bootstrap.min.css" rel="stylesheet">

</head>

<body style="background-color:#FFFFFF">
    @Html.Partial("_HeaderAdmin")




    <div style="width: 100%; height: 300px; margin-bottom: 20px;">
        @RenderBody()
    </div>


    <button class="btnn"
            onclick="topFunction()"
            id="myBtn"
            title="Yukarı Çıkarır">
        Yukarı
    </button>


    @Html.Partial("_Footer")


    <!-- Bootstrap core JavaScript -->

    <script src="~/Models/Scripts/jquery.min.js"></script>
    <script src="~/Models/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Models/Scripts/scripts.js"></script>

</body>

</html>

Kobus/Views/Shared/EmployeeLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="theme-color" content="#272E36" />
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Personel</title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css"
          rel="stylesheet" />
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <link href="~/Content/css/styleslide.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="~/img/FAV.png" />
    <!-- Bootstrap core CSS -->
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/business-casual.min.css" rel="stylesheet">
    <link href="../Content/css/bootstrap.min.css" rel="stylesheet">

</head>

<body style="background-color:#FFFFFF">
    @Html.Partial("_HeaderEmployee")




    <div style="width: 100%; height: 300px; margin-bottom: 20px;">
        @RenderBody()
    </div>


    <button class="btnn"
            onclick="topFunction()"
            id="myBtn"
            title="Yukarı Çıkarır">
        Yukarı
    </button>


    @Html.Partial("_Footer")


    <!-- Bootstrap core JavaScript -->

    <script src="~/Models/Scripts/jquery.min.js"></script>
    <script src="~/Models/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Models/Scripts/scripts.js"></script>

</body>

</html>

Kobus/Views/Shared/LoginLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="theme-color" content="#272E36" />
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Giriş</title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css"
          rel="stylesheet" />
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <link href="~/Content/css/styleslide.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="~/img/FAV.png" />
    <!-- Bootstrap core CSS -->
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/css/business-casual.min.css" rel="stylesheet">
    <link href="../Content/css/bootstrap.min.css" rel="stylesheet">

</head>

<body style="background-color:#FFFFFF">
    @Html.Partial("_Header")




    <div style="width: 100%; height: 300px; margin-bottom: 20px;">
        @RenderBody()
    </div>


    <button class="btnn"
            onclick="topFunction()"
            id="myBtn"
            title="Yukarı Çıkarır">
        Yukarı
    </button>


    @Html.Partial("_Footer")


    <!-- Bootstrap core JavaScript -->

    <script src="~/Models/Scripts/jquery.min.js"></script>
    <script src="~/Models/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Models/Scripts/scripts.js"></script>

</body>

</html>

Kobus/Views/Shared/TicketBus.cshtml
<div class="fila">
    <div class="SeatArea">
        <div class="Seat">
            <input type="checkbox" value="None" id="Seat1" name="check" />
            <label for="Seat1">1</label>
        </div>
        <div class="Seat">
            <input type="checkbox" value="None" id="Seat2" name="check" />
            <label for="Seat2">2</label>
        </div>
    </div>
    <div class="SeatArea">
        <div class="Seat">
            <input type="checkbox" value="None" id="Seat3" name="check" />
            <label for="Seat3">3</label>
        </div>
        <div class="Seat">
            <input type="checkbox" value="None" id="Seat4" name="check" />
            <label for="Seat4">4</label>
        </div>
    </div>
</div>

Kobus/Views/Shared/_Footer.cshtml
<footer class="FooterClass" style="font-size:1em">
    <h3 style="color:#FFFFFF; font-family:'Segoe UI'">Telif hakkı &copy; 2020 Kobus . Tüm hakları saklıdır.</h3>
    <h3 style="color:#5CD375; font-family:'Segoe UI'">Telefon: (0850) 600 00 10</h3>
</footer>

Kobus/Views/Shared/_Header.cshtml
<header style="background-color:#272343">
    <div class="containerr" style="position: relative; padding-bottom:20px">
        <nav>
            <div class="menu-icons">
                <i class="icon ion-md-menu" style="color: #5CD375"></i>
                <i class="icon ion-md-close" style="color: #5CD375"></i>
            </div>
            <a style=""  class="logo">
                <img style="width:18rem;height: 5rem;margin-top:20px"
                     src="~/img/LOGO.png"
                     alt="" />
            </a>
            <ul class="nav-listt">
              
                
                <li>
                    <img style="width: 2.6rem;
                        height: 2.5rem;

                        "
                         src="~/img/kayit.png"
                         alt="" />
                    <a style="margin-left:10px;font-family:'Segoe UI'" href="/Kobus/Login">Yönetici Giriş</a>
                </li>

            </ul>
        </nav>
    </div>
</header>

Kobus/Views/Shared/_HeaderAdmin.cshtml
<header style="background-color:#272343">
    <div class="containerr" style="position: relative; padding-bottom:20px">
        <nav>
            <div class="menu-icons">
                <i class="icon ion-md-menu" style="color: #5CD375"></i>
                <i class="icon ion-md-close" style="color: #5CD375"></i>
            </div>
            <a style="" class="logo">
                <img style="width:18rem;height: 5rem;margin-top:20px"
                     src="~/img/LOGO.png"
                     alt="" />
            </a>
            <ul class="nav-listt">

                <li>
                    <img style="width: 2.3rem;
                        height: 2.3rem;

                        "
                         src="~/img/giris.png"
                         alt="" />
                    <a style="margin-left:10px; font-family:'Segoe UI'" href="/Kobus/Sefer">Sefer İşlemleri</a>
                </li>
                <li>
                    <img style="width: 2.3rem;
                        height: 2.3rem;

                        "
                         src="~/img/giris.png"
                         alt="" />
                    <a style="margin-left:10px;font-family:'Segoe UI'" href="/Kobus/BiletAdmin">Bilet İşlemleri</a>
                </li>

                <li>
                    <img style="width: 2.3rem;
                        height: 2.3rem;

                        "
                         src="~/img/giris.png"
                         alt="" />
                    <a style="margin-left:10px;font-family:'Segoe UI'" href="/Kobus/Login">Çıkış</a>
                </li>

            </ul>
        </nav>
    </div>
</header>